### ISSUE TITLE
fix: RVV Similarity classes missing simdwidth causes compilation failure on riscv64

### ISSUE THREAD

**Issue by CLiqing** [zilliztech/knowhere#1587]
## Description

Compiling knowhere on riscv64 (SG2044 server) fails with:

```
ScalarQuantizerCodec.h:744:36: error: 'simdwidth' is not a member of 'faiss::SimilarityL2_rvv<0>'
  744 |     constexpr int SIMDWIDTH = Sim::simdwidth;
```

## Root Cause

Commit 55c18bb ("Add fallback and uts for sq4u #1421") added a `QT_4bit_uniform` case in `select_distance_computer_rvv` that falls back to the base `select_distance_computer`. The base function requires `Sim::simdwidth`, but `SimilarityL2_rvv<0>` and `SimilarityIP_rvv<0>` only define `metric_type`, missing the `simdwidth` member.

## Steps to Reproduce

Build knowhere on riscv64, or cross-compile with `riscv64-linux-gnu-g++`:

```bash
riscv64-linux-gnu-g++-12 -std=c++17 -c ScalarQuantizerDC_rvv.cpp
```

## Expected Behavior

Compilation succeeds on riscv64.

**Comment by maxiaohong2333** [comment]
On version 2.6.11, I added fix in https://github.com/zilliztech/knowhere/pull/1586.
But I still got compile failure :
I work on  SG2044 + gcc_14.2.0 + "-std=c++17 -march=rv64gcv_zvfhmin".
It won't happen if I use :
        case ScalarQuantizer::QT_4bit_uniform:
            return new DCTemplate_rvv<
                    QuantizerTemplate_rvv<
                            Codec4bit_rvv,
                            QuantizerTemplateScaling::UNIFORM,
                            0>,
                    Similarity,
                    0>(dim, trained);

The build error log:
[build.txt](https://github.com/user-attachments/files/26780070/build.txt)

**Comment by maxiaohong2333** [comment]
The build had passed after PR1586, thank you for your help.
https://github.com/zilliztech/knowhere/pull/1586l

**Comment by alexanderguzhva** [comment]
@maxiaohong2333 would you please also check https://github.com/zilliztech/knowhere/pull/1594, if you have time, of course ? I'm planning to donate the RVV SQ code to vanilla faiss and rely on its Scalar Quantization facilities
