### ISSUE TITLE
knowhere build fail

### ISSUE THREAD

**Issue by cydrain** [zilliztech/knowhere#978]
knowhere build fail with following error messages:
```
/usr/bin/ld: ../libknowhere.so: undefined reference to `sgeqrf_'
/usr/bin/ld: ../libknowhere.so: undefined reference to `sgesvd_'
/usr/bin/ld: ../libknowhere.so: undefined reference to `dsyev_'
/usr/bin/ld: ../libknowhere.so: undefined reference to `sorgqr_'
/usr/bin/ld: ../libknowhere.so: undefined reference to `sgetri_'
/usr/bin/ld: ../libknowhere.so: undefined reference to `dgetri_'
/usr/bin/ld: ../libknowhere.so: undefined reference to `dgetrf_'
/usr/bin/ld: ../libknowhere.so: undefined reference to `sgetrf_'
/usr/bin/ld: ../libknowhere.so: undefined reference to `sgelsd_'
/usr/bin/ld: ../libknowhere.so: undefined reference to `dgesvd_'
collect2: error: ld returned 1 exit status
```

**Comment by cydrain** [comment]
caused by PR #959
